import Navbar from "../Navbar"
import { Providers } from "../Providers"

import "../globals.css"
export const metadata = {
  title: 'gallery',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Navbar bgColor="transparent" textColor="white" />
        
      <Providers>
        
        {children}
       
        </Providers></body>
    </html>
  )
}
